[package]
name = "bastion"
version = "0.1.2"
description = "Fault-tolerant Runtime for Rust applications"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
keywords = ["fault-tolerant", "runtime", "actor", "system"]
categories = []
homepage = "https://github.com/vertexclique/bastion"
repository = "https://github.com/vertexclique/bastion"
documentation = "https://docs.rs/bastion"
readme = "README.md"
license = "MIT"
edition = "2018"
exclude = [
	".github/*",
	"examples/*",
	"graphstore/*",
	"tests/*",
	"img/*",
	"ci/*",
	"benches/*",
	"doc/*",
	"*.png",
	"*.dot",
	"*.yml",
	"*.toml",
	"*.md"
]

[badges]
travis-ci = { repository = "vertexclique/bastion", branch = "master" }
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "^0.1"
tokio-executor = "0.1.8"
tokio-threadpool = "0.1.15"
futures = "0.1.28"
log = "0.4.7"
env_logger = "0.6.1"
crossbeam-channel = "0.3.8"
ratelimit = "0.4.4"
backtrace = "0.3.32"
ego-tree = "0.6.0"
lazy_static = "1.3.0"
objekt = "0.1.2"
signal-hook = "0.1.10"

#futures-preview = "=0.3.0-alpha.16"
uuid = { version = "0.7", features = ["serde", "v4"] }

[dev-dependencies]
reqwest = "0.9.19"

[profile.bench]
panic = "unwind"
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[profile.debug]
panic = "unwind"

[profile.release]
panic = "unwind"
